error = {
    "e-01": "Exporting accounts failed!",
    "e-02": "Importing accounts failed!",
    "e-03": "Please enter name!",
    "e-04": "Please enter type!",
    "e-05": "Failed to add a new account!",
    "e-06": "Exporting transactions failed!",
    "e-07": "Importing transactions failed!",
    "e-08": "Please choose a correct date!",
    "e-09": "Please enter a correct amount!",
    "e-10": "Please enter a category!",
    "e-11": "Please enter a description!",
    "e-12": "Please choose an account!",
    "e-13": "Please enter a sender / receiver!",
    "e-14": "Saving settings failed!",
    "e-15": "Name should contain at least 3 characters!",
    "e-16": "Name should contain fewer than 50 characters!",
    "e-17": "Type should contain at least 3 characters!",
    "e-18": "Type should contain fewer than 50 characters!",
    "e-19": "Please enter an integer or use '.' as the decimal separator!",
    "e-20": "Category should contain at least 3 characters!",
    "e-21": "Category should contain fewer than 50 characters!",
    "e-22": "Description should contain at least 3 characters!",
    "e-23": "Description should contain fewer than 100 characters!",
    "e-24": "Payer / receiver should contain at least 3 characters!",
    "e-25": "Payer / receiver should contain fewer than 50 characters!",
}
